### ISSUE TITLE
tweet.entities  empty

### ISSUE THREAD

**Issue by MyraBaba** [DanielaSfregola/twitter4s-demo#6] opened 2017-01-20 20:30 UTC
Last few days I noticed that tweet entities both media and urls arrays empty even the original tweet has media and url.

I checked include_entities = true in the code. 

Any idea why its not gathering the full entities ?

from the twitter https://dev.twitter.com/rest/tools/console  it shows full entities. but from search its empty.

thx

**Comment by MyraBaba** [comment] 2017-01-20 21:20
Do you think we need to use  tweet_mode=extended ?

**Comment by MyraBaba** [comment] 2017-01-20 23:23
If the Tweets contain the value `truncated:` true then they are extended Tweets and you'll need to use that mode to retrieve the complete object.

I think this is the issue. 

so tweet_mode=extended  could be the solution for rest api parameters...

**Comment by MyraBaba** [comment] 2017-01-21 16:53
I tried with other python client with same query and options (without using tweet_mode)  I can get entities.media links.  

But in twitter4s  always entites.media  is empty.

couldnt find why.

any idea ?

**Comment by DanielaSfregola** [comment] 2017-01-22 08:27
Closing this as duplicate of https://github.com/DanielaSfregola/twitter4s/issues/96

**Closed as completed** 2017-01-22 08:28 UTC
